// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _RelimpPCR_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// dougrizo
int dougrizo(int a, int b);
RcppExport SEXP _RelimpPCR_dougrizo(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dougrizo(a, b));
    return rcpp_result_gen;
END_RCPP
}
// train_test_split_df
List train_test_split_df(DataFrame df, double train_size);
RcppExport SEXP _RelimpPCR_train_test_split_df(SEXP dfSEXP, SEXP train_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type train_size(train_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(train_test_split_df(df, train_size));
    return rcpp_result_gen;
END_RCPP
}
// train_test_split
List train_test_split(DataFrame x, NumericVector y);
RcppExport SEXP _RelimpPCR_train_test_split(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(train_test_split(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RelimpPCR_rcpp_hello_world", (DL_FUNC) &_RelimpPCR_rcpp_hello_world, 0},
    {"_RelimpPCR_dougrizo", (DL_FUNC) &_RelimpPCR_dougrizo, 2},
    {"_RelimpPCR_train_test_split_df", (DL_FUNC) &_RelimpPCR_train_test_split_df, 2},
    {"_RelimpPCR_train_test_split", (DL_FUNC) &_RelimpPCR_train_test_split, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RelimpPCR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
