# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_RelimpPCR_rcpp_hello_world`)
}

dougrizo <- function(a, b) {
    .Call(`_RelimpPCR_dougrizo`, a, b)
}

train_test_split_df <- function(df, train_size = 0.7) {
    .Call(`_RelimpPCR_train_test_split_df`, df, train_size)
}

train_test_split <- function(x, y) {
    .Call(`_RelimpPCR_train_test_split`, x, y)
}

