# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize_df_r <- function(x) {
    .Call(`_RelimpPCR_normalize_df_r`, x)
}

RelimpPCR <- function(x, y, train_size) {
    .Call(`_RelimpPCR_RelimpPCR`, x, y, train_size)
}

train_test_split_r <- function(x, y, train_size) {
    .Call(`_RelimpPCR_train_test_split_r`, x, y, train_size)
}

