// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// remove_col_r
void remove_col_r(Rcpp::NumericMatrix x, int mcol);
RcppExport SEXP _RelimpPCR_remove_col_r(SEXP xSEXP, SEXP mcolSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type mcol(mcolSEXP);
    remove_col_r(x, mcol);
    return R_NilValue;
END_RCPP
}
// split_and_normalize_r
Rcpp::List split_and_normalize_r(Rcpp::NumericMatrix x, Rcpp::NumericVector y, double train_size);
RcppExport SEXP _RelimpPCR_split_and_normalize_r(SEXP xSEXP, SEXP ySEXP, SEXP train_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type train_size(train_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(split_and_normalize_r(x, y, train_size));
    return rcpp_result_gen;
END_RCPP
}
// backwards_step_princomp_r
Rcpp::List backwards_step_princomp_r(Rcpp::NumericMatrix x);
RcppExport SEXP _RelimpPCR_backwards_step_princomp_r(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(backwards_step_princomp_r(x));
    return rcpp_result_gen;
END_RCPP
}
// RelimpPCR
Rcpp::NumericMatrix RelimpPCR(Rcpp::NumericMatrix x, Rcpp::NumericVector y, double train_size);
RcppExport SEXP _RelimpPCR_RelimpPCR(SEXP xSEXP, SEXP ySEXP, SEXP train_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type train_size(train_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(RelimpPCR(x, y, train_size));
    return rcpp_result_gen;
END_RCPP
}
// train_test_split_r
Rcpp::List train_test_split_r(Rcpp::NumericMatrix x, Rcpp::NumericVector y, double train_size);
RcppExport SEXP _RelimpPCR_train_test_split_r(SEXP xSEXP, SEXP ySEXP, SEXP train_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type train_size(train_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(train_test_split_r(x, y, train_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RelimpPCR_remove_col_r", (DL_FUNC) &_RelimpPCR_remove_col_r, 2},
    {"_RelimpPCR_split_and_normalize_r", (DL_FUNC) &_RelimpPCR_split_and_normalize_r, 3},
    {"_RelimpPCR_backwards_step_princomp_r", (DL_FUNC) &_RelimpPCR_backwards_step_princomp_r, 1},
    {"_RelimpPCR_RelimpPCR", (DL_FUNC) &_RelimpPCR_RelimpPCR, 3},
    {"_RelimpPCR_train_test_split_r", (DL_FUNC) &_RelimpPCR_train_test_split_r, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RelimpPCR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
