RelimpPCR.bootstrap = function(X,Y,target_r2,validation_split,iterations,bootstrap_plot = T, relimp_algorithm="last",max_predictors=0,
                               max_factors_to_remove=15,normalize_data=T,multicore=T,cores=2){
  if(iterations>100){
    warning("This number of iterations may take a very very long time to run - especially with large data sets.")
  }
  
  if(validation_split == 1){
    stop("You cannot perform RelimpPCR.bootstrap with validation split of 1.")
  }
  
  #Difference between relimp_pca_r2 AND mean of others.
  r2_diff_mean = matrix(data = 0, ncol = 2, nrow = iterations)
  
  #Difference between relimp_pca_r2 AND max of others.
  r2_diff_max = matrix(data = 0, ncol = 2, nrow = iterations)
  
  #The rankings for each iteration.
  rankings = matrix(data = 0, ncol = ncol(X), nrow = iterations)
  
  #The best model coefficients for each iteration.
  coefs = as.data.frame(matrix(data = NA, ncol = ncol(X), nrow = iterations))
  
  coefs_colnames = c()
  for(i in 1:ncol(coefs)){
    coefs_colnames[length(coefs_colnames)+1] = paste0("PC",i)
  }
  colnames(coefs) = coefs_colnames
  
  for(i in 1:iterations){
    print(paste0("ITERATION ",i))
    pcr = RelimpPCR(X = X, Y = Y, target_r2 = target_r2, validation_split = validation_split, relimp_algorithm = relimp_algorithm, max_predictors = max_predictors,
                    max_factors_to_remove = max_factors_to_remove, normalize_data = normalize_data, plot_this = F, verbose = F, multicore = multicore, cores = cores)
    if("relimp_r2_train" %in% names(pcr)){
      mean_train = mean(pcr$relimp_r2_train[pcr$num_factors], pcr$pca_r2_train[pcr$num_factors], pcr$original_r2_train[pcr$num_factors])
      mean_test = mean(pcr$relimp_r2_test[pcr$num_factors], pcr$pca_r2_test[pcr$num_factors], pcr$original_r2_test[pcr$num_factors])
      max_train = max(pcr$relimp_r2_train[pcr$num_factors], pcr$pca_r2_train[pcr$num_factors], pcr$original_r2_train[pcr$num_factors])
      max_test = max(pcr$relimp_r2_test[pcr$num_factors], pcr$pca_r2_test[pcr$num_factors], pcr$original_r2_test[pcr$num_factors])
    } else {
      mean_train = mean(pcr$pca_r2_train[pcr$num_factors], pcr$original_r2_train[pcr$num_factors])
      mean_test = mean(pcr$pca_r2_test[pcr$num_factors], pcr$original_r2_test[pcr$num_factors])
      max_train = max(pcr$pca_r2_train[pcr$num_factors], pcr$original_r2_train[pcr$num_factors])
      max_test = max(pcr$pca_r2_test[pcr$num_factors], pcr$original_r2_test[pcr$num_factors])
    }
      r2_diff_mean[i,1] = pcr$relimp_pca_r2_train[pcr$num_factors] - mean_train
      r2_diff_mean[i,2] = pcr$relimp_pca_r2_test[pcr$num_factors] - mean_test
      r2_diff_max[i,1] = pcr$relimp_pca_r2_train[pcr$num_factors] - max_train
      r2_diff_max[i,2] = pcr$relimp_pca_r2_test[pcr$num_factors] - max_test
      
      rankings[i,] = pcr$pca_factors_rank
      
      for(name in names(pcr$best_model$coefficients)){
        if(name == "(Intercept)"){
          next
        } else {
          coefs[i,name] = as.numeric(pcr$best_model$coefficients[name])
        }
      }
  }
  if(bootstrap_plot==T){
    ggplot_df = cbind(r2_diff_mean,r2_diff_max)
    colnames(ggplot_df) = c("Train - Mean","Test - Mean","Train - Max","Test - Max")
    ggplot_df = reshape2::melt(data = ggplot_df)
    p1 = ggplot2::ggplot(data = ggplot_df, ggplot2::aes(Var2,value)) +
      ggplot2::geom_boxplot() + 
      ggplot2::geom_jitter(width = 0.1) + 
      ggplot2::labs(x="Difference Type",y="Difference Between Optimal PCA Relimp R2 and Other R2's") + 
      ggplot2::ggtitle("Surplus/Deficit R2 Generated by Relimp PCA")
    print(p1)
  }
  
  return(list("r2_diff_mean"=r2_diff_mean,"r2_diff_max"=r2_diff_max,"rankings"=rankings,"coefficients"=coefs))
  
}